---
title: "Set_13_SETAR_sim"
output: html_notebook
---

Set data directory path
```{r setup, include=FALSE, cache = FALSE}
if (!require("knitr")) install.packages("knitr")
library(knitr)
opts_knit$set(root.dir = "C:/Teaching/Undergrad/data ECO374")
```

Install and load required packages
```{r}
library(xts)
```

Simulate and plot SETAR process
```{r}
phi1 <- 0.9
phi2 <- 0.3
n <- 1000
eps <- rnorm(n, mean=0, sd=0.25)
y <- seq(0,0,length.out=n)
y[1] <- eps[1]

for (t in 2:n) {

   if (y[t-1]>0)  {
      y[t] <- phi1*y[t-1] + eps[t]
   } 
   else {
      y[t] <- phi2*y[t-1] + eps[t]
   }

}

plot(y, type="l")
abline(h=0)

```

Histogram of SETAR draws
```{r}
hist(y, prob = TRUE, breaks=100, xlim=c(-2,2), col="lightgrey", main="Histogram of SETAR draws", cex.main=0.85)
```

ACF and PACF of SETAR draws, indicating the order of a linear AR approximation to the SETAR process
```{r}
maxlag <- 30
ACF <- acf(y, lag.max=maxlag, plot=FALSE)
PACF <- pacf(y, lag.max=maxlag, plot=FALSE)
par(mfcol=c(1,2), mai=c(0.4, 0.4, 0.7, 0.1), cex.main=0.9)
plot(ACF[1:maxlag], main="ACF of SETAR draws")
plot(PACF[1:maxlag], ylim=c(-0.1,1), main="PACF of SETAR draws")
```

